// Copyright 2026 The ODML Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef THIRD_PARTY_ODML_LITERT_LM_RUNTIME_COMPONENTS_LOGITS_PROCESSOR_LOGITS_PROCESSOR_H_
#define THIRD_PARTY_ODML_LITERT_LM_RUNTIME_COMPONENTS_LOGITS_PROCESSOR_LOGITS_PROCESSOR_H_

#include "absl/status/status.h"  // from @com_google_absl
#include "absl/types/span.h"  // from @com_google_absl
#include "litert/cc/litert_layout.h"  // from @litert
#include "litert/cc/litert_tensor_buffer.h"  // from @litert
#include "tflite/types/half.h"  // from @litert

namespace litert::lm {

class ConstrainedDecoder;

// `LogitsProcessor` is an abstract interface for components that dynamically
// modify the model's output logits prior to token sampling.
//
// Logit processors operate sequentially in the generation loop:
// 1. `ProcessLogits` is called with the raw logits generated by the model for
//    the current step. The processor modifies the logits in-place to encourage,
//    discourage, or strictly constrain the selection of certain tokens based on
//    its internal logic (e.g. banning tokens, penalizing repetition, enforcing
//    formal grammar constraints).
// 2. The sampler selects a token from the modified logits.
// 3. `UpdateState` is called with the selected token, allowing the processor to
//    update its internal history or state machine.
class LogitsProcessor {
 public:
  virtual ~LogitsProcessor() = default;

  // Modifies the logits tensor in-place based on the processor's current state.
  //
  // @param logits A tensor of shape [batch_size, sequence_length, vocab_size],
  // where sequence_length must always be exactly 1 as processors only support
  // single token decoding per step. Contains the logits for the next token
  // prediction. This tensor is modified in-place.
  // @return Ok if masking was successful, or an error if dimensions are
  // incorrect or masking fails.
  virtual absl::Status ProcessLogits(::litert::TensorBuffer& logits) = 0;

  // Same as above, but takes a span of float logits instead of a tensor buffer.
  virtual absl::Status ProcessLogits(
      absl::Span<float> logits,
      absl::Span<const ::litert::Layout::Dim> logits_dims) = 0;

  // Same as above, but takes a span of half logits instead of a tensor buffer.
  virtual absl::Status ProcessLogits(
      absl::Span<tflite::half> logits,
      absl::Span<const ::litert::Layout::Dim> logits_dims) = 0;

  // Updates the processor's internal sequence history based on the newly
  // selected tokens.
  //
  // @param next_token_ids A tensor of shape [batch_size, sequence_length],
  // where sequence_length must always be exactly 1 as processors only support
  // single token decoding per step. Contains the token ID selected for each
  // sequence in the batch for the current step.
  //
  // @return Ok if the state was updated successfully, or an error if any token
  // is invalid for its corresponding state.
  virtual absl::Status UpdateState(
      const ::litert::TensorBuffer& next_token_ids) = 0;

  // Same as above, but takes a span of token ids instead of a tensor buffer.
  //
  // @param next_token_ids A span of int token IDs, where the length must always
  // be exactly batch_size.
  //
  // @return Ok if the state was updated successfully, or an error if any token
  // is invalid for its corresponding state.
  virtual absl::Status UpdateState(absl::Span<int> next_token_ids) = 0;

  // Returns the constraint decoder if it exists. Otherwise, returns nullptr.
  //
  // TODO(b/517779380): Remove this method once the logits processor is fully
  // supported in the hand-written path.
  virtual ConstrainedDecoder* GetConstraintDecoder() { return nullptr; }

  // Save as above, but returns a const pointer.
  //
  // TODO(b/517779380): Remove this method once the logits processor is fully
  // supported in the hand-written path.
  virtual const ConstrainedDecoder* GetConstraintDecoder() const {
    return nullptr;
  }
};

}  // namespace litert::lm

#endif  // THIRD_PARTY_ODML_LITERT_LM_RUNTIME_COMPONENTS_CONSTRAINED_DECODING_LOGITS_PROCESSOR_H_
