# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


include(ExternalProject)

set(LITERT_EXT_PREFIX    ${EXTERNAL_PROJECT_BINARY_DIR}/litert CACHE INTERNAL "")
set(LITERT_BUILD_DIR     ${LITERT_EXT_PREFIX}/src/litert_external-build CACHE INTERNAL "")
set(LITERT_SOURCE_DIR    ${LITERT_EXT_PREFIX}/src/litert_external CACHE INTERNAL "")
set(LITERT_SRC_DIR       "${LITERT_SOURCE_DIR}/litert" CACHE INTERNAL "")
set(LITERT_INCLUDE_PATHS
  ${LITERT_SOURCE_DIR}
  ${LITERT_BUILD_DIR}/include
  ${LITERT_BUILD_DIR}/c/include
  ${LITERT_BUILD_DIR}/cc/include
  ${LITERT_BUILD_DIR}/compiler/include
  ${LITERT_BUILD_DIR}/core/include
  ${LITERT_BUILD_DIR}/runtime/include
CACHE INTERNAL "")
set(LITERT_CXX_FLAGS_Construct "${CMAKE_CXX_FLAGS} -fpermissive")

if(OPENCL_INCLUDE_DIR)
  string(APPEND LITERT_CXX_FLAGS_Construct " -isystem ${OPENCL_INCLUDE_DIR}")
endif()

ExternalProject_Add(
  litert_external
  DEPENDS
    opencl_headers_external
    absl_external
    protobuf_external
    flatbuffers_external
    tflite_external

  GIT_REPOSITORY
    https://github.com/google-ai-edge/LiteRT.git
  GIT_TAG
    fb16353a648922cb6c67a8e9a7a9ebc946360ad2 #Updated on 2026-03-24
  GIT_SUBMODULES ""
  GIT_SUBMODULES_RECURSE FALSE
  PREFIX
    ${LITERT_EXT_PREFIX}
  SOURCE_SUBDIR
    litert
  PATCH_COMMAND
    git checkout -- . && git clean -df

    COMMAND ${CMAKE_COMMAND}
    -DCMAKE_INSTALL_LIBDIR=lib
    -DFLATC_EXECUTABLE=${FLATC_EXECUTABLE}
    -DFLATBUFFERS_LIB_DIR=${FLATBUFFERS_LIB_DIR}
    -DTFLITE_SRC_DIR=${TFLITE_SRC_DIR}
    -DTFLITE_BUILD_DIR=${TFLITE_BUILD_DIR}
    -DTFLITE_LIB_DIR=${TFLITE_LIB_DIR}
    -DTFLITE_PACKAGE_DIR=${TFLITE_PACKAGE_DIR}
    -DTENSORFLOW_SOURCE_DIR=${TENSORFLOW_SOURCE_DIR}
    -DLITERTLM_PACKAGES_DIR=${LITERTLM_PACKAGES_DIR}
    -DLITERTLM_MODULES_DIR=${LITERTLM_MODULES_DIR}
    -DLITERT_SOURCE_DIR=${LITERT_SOURCE_DIR}
    -DABSL_LIBS_FLAT=${ABSL_LIBS_FLAT}
    -DABSL_INCLUDE_DIR=${ABSL_INCLUDE_DIR}
    -DOPENCL_INCLUDE_DIR=${OPENCL_INCLUDE_DIR}
    -DJSON_INCLUDE_DIR=${JSON_SRC_DIR}
    -DLITERT_SRC_DIR=${LITERT_SRC_DIR}
    -DLITERT_PACKAGE_DIR=${LITERT_PACKAGE_DIR}
    -DLITERT_BUILD_CONFIG_DISABLE_GPU_VAL=${LITERT_BUILD_CONFIG_DISABLE_GPU_VAL}
    -DLITERT_BUILD_CONFIG_DISABLE_NPU_VAL=${LITERT_BUILD_CONFIG_DISABLE_NPU_VAL}
    -P "${LITERT_PACKAGE_DIR}/litert_patcher.cmake"

  CMAKE_ARGS
    ${LITERTLM_TOOLCHAIN_FILE}
    ${LITERTLM_TOOLCHAIN_ARGS}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5
    -DCMAKE_POLICY_DEFAULT_CMP0169=OLD
    -DCMAKE_POLICY_DEFAULT_CMP0170=OLD
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    -DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD}
    -DCMAKE_CXX_STANDARD_REQUIRED=ON
    -DCMAKE_CXX_EXTENSIONS=OFF
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON
    "-DCMAKE_PREFIX_PATH=${ABSL_INSTALL_PREFIX};${TFLITE_INSTALL_PREFIX};${PROTOBUF_INSTALL_PREFIX};${FLATBUFFERS_INSTALL_PREFIX}"
    "-DCMAKE_CXX_FLAGS:STRING=${LITERT_CXX_FLAGS_Construct} -isystem ${TFLITE_INSTALL_PREFIX}/include -isystem ${ABSL_INSTALL_PREFIX}/include -isystem ${PROTOBUF_INSTALL_PREFIX}/include -w"
    "-DCMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS} -isystem ${TFLITE_INSTALL_PREFIX}/include"

    -DCL_TARGET_OPENCL_VERSION=220
    -DCL_HPP_TARGET_OPENCL_VERSION=220
    -DCL_HPP_MIN_TARGET_OPENCL_VERSION=220

    "-D_abseil-cpp_LICENSE_FILE:FILEPATH=${ABSL_EXT_PREFIX}/src/absl_external/LICENSE"
    "-DFETCHCONTENT_SOURCE_DIR_ABSEIL-CPP=${ABSL_EXT_PREFIX}/src/absl_external"
    -Dabsl_SOURCE_DIR=${ABSL_SRC_DIR}
    -Dabsl_BINARY_DIR=${ABSL_BUILD_DIR}
    -Dabsl_INCLUDE_DIR=${ABSL_INCLUDE_DIR}
    -DABSL_INCLUDE_DIR=${ABSL_INCLUDE_DIR}
    -DABSL_LIBRARIES=${ABSL_LIB_DIR}
    -Dabsl_DIR=${ABSL_LIB_DIR}/cmake/absl

    -DFLATBUFFERS_BUILD_FLATC=OFF
    -DFLATBUFFERS_INSTALL=OFF
    -DFLATBUFFERS_PROJECT_DIR=${FLATBUFFERS_SRC_DIR}/flatbuffers_external
    -DFlatBuffers_BINARY_DIR=${FLATBUFFERS_BIN_DIR}
    -DFlatBuffers_SOURCE_DIR=${FLATBUFFERS_SRC_DIR}/flatbuffers_external
    -D_flatbuffers_LICENSE_FILE:FILEPATH=${FLATBUFFERS_SRC_DIR}/flatbuffers_external/LICENSE
    -DFLATC_PATHS=${FLATBUFFERS_BIN_DIR}
    -DFLATBUFFERS_FLATC_EXECUTABLE=${FLATC_EXECUTABLE}
    -DFLATC_EXECUTABLE=${FLATC_EXECUTABLE}
    -Dflatbuffers_DIR=${FLATBUFFERS_INSTALL_PREFIX}/lib/cmake/flatbuffers
    -DFETCHCONTENT_SOURCE_DIR_FLATBUFFERS=${FLATBUFFERS_SRC_DIR}/flatbuffers_external
    -DFLATBUFFERS_INSTALL_PREFIX=${FLATBUFFERS_INSTALL_PREFIX}
    -DFLATBUFFERS_LIB_DIR=${FLATBUFFERS_LIB_DIR}
    -DFLATBUFFERS_INCLUDE_DIR=${FLATBUFFERS_INCLUDE_DIR}
    -DFLATC_EXECUTABLE=${FLATC_EXECUTABLE}

    -DTFLite_DIR=${TFLITE_INSTALL_PREFIX}/lib
    -Dtensorflow-lite_DIR=${TFLITE_INSTALL_PREFIX}/lib
    -DTFLITE_BUILD_DIR=${TFLITE_BUILD_DIR}
    -DTFLITE_SOURCE_DIR=${TFLITE_SRC_DIR}
    -DTENSORFLOW_SOURCE_DIR=${TENSORFLOW_SOURCE_DIR}

    -DLITERT_AUTO_BUILD_TFLITE=OFF
    -DTFLITE_ENABLE_INSTALL=OFF
    -DTFLITE_ENABLE_XNNPACK=ON
    -DTFLITE_ENABLE_RESOURCE_VARIABLE=OFF
    -DXNNPACK_SET_VERBOSITY=OFF
    -DTFLITE_ENABLE_GPU=OFF
    -DLITERT_ENABLE_GPU=OFF
    -DLITERT_ENABLE_NPU=ON
    -DLITERT_ENABLE_QUALCOMM=ON
    -DLITERT_DISABLE_KLEIDIAI=ON
    -DLITERT_BUILD_C_API=ON
    -DLITERT_BUILD_TOOLS=OFF
    "-DCMAKE_EXE_LINKER_FLAGS=-L${ABSL_LIB_DIR} -L${PROTO_LIB_DIR} -L${FLATBUFFERS_LIB_DIR} -L${TFLITE_LIB_DIR}"

    # TODO(totero): Organize these flags.
    -DLITERTLM_MODULES_DIR=${LITERTLM_MODULES_DIR}

    -DTFLITE_SRC_DIR=${TFLITE_SRC_DIR}
    -DTFLITE_PACKAGE_DIR=${TFLITE_PACKAGE_DIR}
    -DTENSORFLOW_SOURCE_DIR=${TENSORFLOW_SOURCE_DIR}
    -DLITERTLM_PACKAGES_DIR=${LITERTLM_PACKAGES_DIR}
    -DLITERTLM_MODULES_DIR=${LITERTLM_MODULES_DIR}
    -DLITERT_SOURCE_DIR=${LITERT_SOURCE_DIR}
    -DABSL_LIBS_FLAT=${ABSL_LIBS_FLAT}
    -DABSL_LIB_DIR=${ABSL_LIB_DIR}
    -DABSL_INCLUDE_DIR=${ABSL_INCLUDE_DIR}
    -DOPENCL_INCLUDE_DIR=${OPENCL_INCLUDE_DIR}
    -DJSON_INCLUDE_DIR=${JSON_SRC_DIR}
    -DLITERT_SRC_DIR=${LITERT_SRC_DIR}
    -DTFLITE_FORCE_LOAD_TARGETS=${TFLITE_FORCE_LOAD_TARGETS}
    -DTFLITE_STANDARD_TARGETS=${TFLITE_STANDARD_TARGETS}
    -DTFLITE_INCLUDE_DIR=${TFLITE_INCLUDE_DIR}
    -DTFLITE_BUILD_DIR=${TFLITE_BUILD_DIR}
    -DTFLITE_LIB_DIR=${TFLITE_LIB_DIR}
    -DPROTO_LIB_DIR=${PROTO_LIB_DIR}
    -DXNNPACK_SOURCE_DIR=${XNNPACK_SOURCE_DIR}
    -DXNNPACK_BINARY_DIR=${XNNPACK_BINARY_DIR}
    -DXNNPACK_INCLUDE_DIR=${XNNPACK_INCLUDE_DIR}
    -DXNNPACK_LIB_DIR=${XNNPACK_LIB_DIR}
    -DPROTO_PROTOC_EXECUTABLE=${PROTO_PROTOC_EXECUTABLE}

  INSTALL_COMMAND ""
)

include(${LITERT_PACKAGE_DIR}/litert_aggregate.cmake)
generate_litert_aggregate()
