/**
 * Copyright 2026 The ODML Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {SessionConfig} from './session_config.js';
import {JsonValue} from './types.js';

/**
 * A parameter schema definition, adhering to a subset of JSON Schema.
 */
export interface Schema {
  type?: 'object'|'array'|'string'|'number'|'integer'|'boolean'|'null';
  description?: string;
  properties?: Record<string, Schema>;
  required?: string[];
  items?: Schema;
  enum?: string[];
}

/**
 * Declaration of a function that the model can call.
 */
export interface FunctionDeclaration {
  name: string;
  description?: string;
  parameters?: Schema;
  response?: Schema;  // Optional response schema declaration for the tool.
}

/**
 * A wrapper for a function tool. This is the canonical format
 * generated by platform SDKs.
 */
export declare interface FunctionTool {
  type: string;
  function: FunctionDeclaration;
  [key: string]: JsonValue|FunctionDeclaration|undefined;
}

/**
 * A tool that can be provided to the model.
 * The C++ runtime is flexible and accepts both wrapped and unwrapped formats.
 */
export type Tool = FunctionDeclaration|FunctionTool;

/**
 * Any support content part in a message.
 */
export type ContentPart = TextContentPart|ImageContentPart|AudioContentPart|
    VideoContentPart|ToolResponsePart;

/**
 * Text content part of a message.
 */
export interface TextContentPart {
  type: 'text';
  text: string;
  [key: string]: JsonValue|undefined;
}

/**
 * Image content part of a message.
 *
 * This is a placeholder. Images are not supported in JS yet.
 */
export interface ImageContentPart {
  type: 'image';
  [key: string]: JsonValue|undefined;
}

/**
 * Audio content part of a message.
 *
 * This is a placeholder. Audio is not supported in JS yet.
 */
export interface AudioContentPart {
  type: 'audio';
  [key: string]: JsonValue|undefined;
}

/**
 * Video content part of a message.
 *
 * This is a placeholder. Video is not supported in JS yet.
 */
export interface VideoContentPart {
  type: 'video';
  [key: string]: JsonValue|undefined;
}

/**
 * The response from a tool execution.
 */
export declare interface ToolResponsePart {
  type: 'tool_response';
  name?: string;  // The name of the tool that was executed.
  response?: JsonValue;
  value?: JsonValue;
  [key: string]: JsonValue|undefined;
}

/**
 * A function call predicted by the model.
 */
export declare interface ToolCallFunction {
  name: string;
  arguments: Record<string, JsonValue>;
  [key: string]: JsonValue|undefined;
}

/**
 * A tool call in the message.
 */
export declare interface ToolCall {
  type: string;
  id?: string;  // Unique identifier for the tool call.
  function: ToolCallFunction;
  [key: string]: JsonValue|undefined;
}

/**
 * A message in the conversation.
 */
export declare interface Message {
  role: string;
  content?: string|ContentPart[];
  channels?: Record<string, string>;
  tool_calls?: ToolCall[];
  [key: string]: JsonValue|undefined;
}

/**
 * Types that can be used as a Message in the conversation.
 */
export type MessageLike = string|Message;

/**
 * Preface is the initial messages, tools and extra context for the
 * conversation to begin with. It provides the initial background for the
 * conversation.
 */
export declare interface Preface {
  // The messages in the preface. The messages provided the initial background
  // for the conversation. For example, the messages can be the conversation
  // history, prompt engineering instructions, few-shot examples, etc.
  messages?: Message[];
  // The tools able to be used by the model in the conversation.
  tools?: Tool[];
  // The extra context that is not part of the messages or tools. This is can be
  // extended by the model to support other features. For example, configurable
  // template rendering or other model-specific features.
  extra_context?: Record<string, JsonValue>;
  [key: string]: unknown;
}

/**
 * Configuration for the Conversation instance.
 */
export declare interface ConversationConfig {
  sessionConfig?: SessionConfig;
  preface?: Preface;
  enableConstrainedDecoding?: boolean;
  prefillPrefaceOnInit?: boolean;
  filterChannelContentFromKvCache?: boolean;
  // TODO: b/477709280 - Add support for custom channel arrays.
}
